


export const EVENT_TYPES = [
  "Hackathon",
  "Seminar",
  "Workshop"
];

export const FEATURED_EVENTS = [
  {
    id: 1,
    title: "AI Innovation Hackathon",
    type: "Hackathon",
    description: "Build AI solutions for real-world problems in 48 hours",
    image: "/images/hackathon-ai.jpg",
    date: "2023-12-15T09:00:00",
    venue: "Tech Park, Bangalore",
    seats: 120,
    registered: 89,
  },
  {
    id: 2,
    title: "Web3 Security Seminar",
    type: "Seminar",
    description: "Learn about blockchain security best practices",
    image: "/images/seminar-web3.jpg",
    date: "2023-11-28T14:00:00",
    venue: "Convention Center, Delhi",
    seats: 200,
    registered: 145,
  },
  {
  "id": 3,
  "title": "HealthTech Challenge",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-3.jpg",
  "date": "2024-01-30T00:00:00",
  "venue": "Innovation Hub, Mumbai",
  "seats": 193,
  "registered": 147
},
  {
  "id": 4,
  "title": "AR/VR Design Workshop",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-4.jpg",
  "date": "2024-01-29T00:00:00",
  "venue": "Knowledge Hall, Jaipur",
  "seats": 233,
  "registered": 181
},
  {
  "id": 5,
  "title": "AI Ethics Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-5.jpg",
  "date": "2024-01-23T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 94,
  "registered": 139
},
  {
  "id": 6,
  "title": "Next.js Masterclass",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-6.jpg",
  "date": "2024-02-28T00:00:00",
  "venue": "Knowledge Hall, Jaipur",
  "seats": 250,
  "registered": 214
},
  {
  "id": 7,
  "title": "Blockchain Basics",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-7.jpg",
  "date": "2024-03-06T00:00:00",
  "venue": "DevHub, Chennai",
  "seats": 100,
  "registered": 70
},
  {
  "id": 8,
  "title": "Docker Deep Dive",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-8.jpg",
  "date": "2023-12-12T00:00:00",
  "venue": "Tech Park, Bangalore",
  "seats": 280,
  "registered": 98
},
  {
  "id": 9,
  "title": "Next.js Masterclass",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-9.jpg",
  "date": "2024-02-22T00:00:00",
  "venue": "Creator Space, Kochi",
  "seats": 74,
  "registered": 140
},
  {
  "id": 10,
  "title": "Blockchain Basics",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-10.jpg",
  "date": "2024-03-19T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 281,
  "registered": 78
},
  {
  "id": 11,
  "title": "HealthTech Challenge",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-11.jpg",
  "date": "2024-01-11T00:00:00",
  "venue": "DevHub, Chennai",
  "seats": 192,
  "registered": 223
},
  {
  "id": 12,
  "title": "Python for Data Science",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-12.jpg",
  "date": "2024-03-21T00:00:00",
  "venue": "DevHub, Chennai",
  "seats": 213,
  "registered": 33
},
  {
  "id": 13,
  "title": "Blockchain Basics",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-13.jpg",
  "date": "2024-03-14T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 227,
  "registered": 69
},
  {
  "id": 14,
  "title": "Blockchain Basics",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-14.jpg",
  "date": "2024-03-13T00:00:00",
  "venue": "DevHub, Chennai",
  "seats": 119,
  "registered": 203
},
  {
  "id": 15,
  "title": "Python for Data Science",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-15.jpg",
  "date": "2023-11-29T00:00:00",
  "venue": "IT Convention Center, Pune",
  "seats": 214,
  "registered": 202
},
  {
  "id": 16,
  "title": "AI Ethics Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-16.jpg",
  "date": "2024-03-21T00:00:00",
  "venue": "IT Convention Center, Pune",
  "seats": 143,
  "registered": 97
},
  {
  "id": 17,
  "title": "Future Code Hackathon",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-17.jpg",
  "date": "2024-04-28T00:00:00",
  "venue": "Creator Space, Kochi",
  "seats": 95,
  "registered": 126
},
  {
  "id": 18,
  "title": "AI Innovation Hackathon",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-18.jpg",
  "date": "2024-04-13T00:00:00",
  "venue": "Tech Park, Bangalore",
  "seats": 272,
  "registered": 96
},
  {
  "id": 19,
  "title": "Cloud Native Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-19.jpg",
  "date": "2023-12-27T00:00:00",
  "venue": "Innovation Hub, Mumbai",
  "seats": 174,
  "registered": 213
},
  {
  "id": 20,
  "title": "Cyber Law Session",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-20.jpg",
  "date": "2024-03-19T00:00:00",
  "venue": "Innovation Hub, Mumbai",
  "seats": 207,
  "registered": 53
},
  {
  "id": 21,
  "title": "AR/VR Design Workshop",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-21.jpg",
  "date": "2024-03-28T00:00:00",
  "venue": "DevHub, Chennai",
  "seats": 136,
  "registered": 17
},
  {
  "id": 22,
  "title": "Blockchain Basics",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-22.jpg",
  "date": "2024-01-20T00:00:00",
  "venue": "IT Convention Center, Pune",
  "seats": 263,
  "registered": 142
},
  {
  "id": 23,
  "title": "React Native Bootcamp",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-23.jpg",
  "date": "2024-04-15T00:00:00",
  "venue": "IT Convention Center, Pune",
  "seats": 203,
  "registered": 39
},
  {
  "id": 24,
  "title": "HealthTech Challenge",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-24.jpg",
  "date": "2023-12-27T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 173,
  "registered": 106
},
  {
  "id": 25,
  "title": "AI Innovation Hackathon",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-25.jpg",
  "date": "2024-03-18T00:00:00",
  "venue": "Digital Valley, Indore",
  "seats": 243,
  "registered": 28
},
  {
  "id": 26,
  "title": "Next.js Masterclass",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-26.jpg",
  "date": "2024-03-17T00:00:00",
  "venue": "Innovation Hub, Mumbai",
  "seats": 285,
  "registered": 62
},
  {
  "id": 27,
  "title": "Cloud Native Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-27.jpg",
  "date": "2024-01-27T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 209,
  "registered": 77
},
  {
  "id": 28,
  "title": "AI Innovation Hackathon",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-28.jpg",
  "date": "2024-03-06T00:00:00",
  "venue": "Tech Park, Bangalore",
  "seats": 147,
  "registered": 13
},
  {
  "id": 29,
  "title": "React Native Bootcamp",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-29.jpg",
  "date": "2024-02-26T00:00:00",
  "venue": "Digital Valley, Indore",
  "seats": 111,
  "registered": 162
},
  {
  "id": 30,
  "title": "Cloud Native Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-30.jpg",
  "date": "2024-03-14T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 285,
  "registered": 57
},
  {
  "id": 31,
  "title": "GreenTech Sprint",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-31.jpg",
  "date": "2023-11-18T00:00:00",
  "venue": "Tech Park, Bangalore",
  "seats": 73,
  "registered": 14
},
  {
  "id": 32,
  "title": "Blockchain Basics",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-32.jpg",
  "date": "2023-12-30T00:00:00",
  "venue": "Tech Park, Bangalore",
  "seats": 270,
  "registered": 243
},
  {
  "id": 33,
  "title": "Blockchain Basics",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-33.jpg",
  "date": "2023-11-14T00:00:00",
  "venue": "Creator Space, Kochi",
  "seats": 273,
  "registered": 172
},
  {
  "id": 34,
  "title": "Next.js Masterclass",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-34.jpg",
  "date": "2024-03-22T00:00:00",
  "venue": "Innovation Hub, Mumbai",
  "seats": 205,
  "registered": 240
},
  {
  "id": 35,
  "title": "AR/VR Design Workshop",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-35.jpg",
  "date": "2024-03-11T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 172,
  "registered": 94
},
  {
  "id": 36,
  "title": "React Native Bootcamp",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-36.jpg",
  "date": "2024-01-24T00:00:00",
  "venue": "Digital Valley, Indore",
  "seats": 86,
  "registered": 230
},
  {
  "id": 37,
  "title": "SpaceTech Hack",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-37.jpg",
  "date": "2024-04-03T00:00:00",
  "venue": "Digital Valley, Indore",
  "seats": 51,
  "registered": 223
},
  {
  "id": 38,
  "title": "AI Innovation Hackathon",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-38.jpg",
  "date": "2024-01-23T00:00:00",
  "venue": "Creator Space, Kochi",
  "seats": 88,
  "registered": 45
},
  {
  "id": 39,
  "title": "Web3 Security Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-39.jpg",
  "date": "2024-02-10T00:00:00",
  "venue": "Startup Arena, Hyderabad",
  "seats": 285,
  "registered": 153
},
  {
  "id": 40,
  "title": "Docker Deep Dive",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-40.jpg",
  "date": "2024-01-09T00:00:00",
  "venue": "Digital Valley, Indore",
  "seats": 157,
  "registered": 195
},
  {
  "id": 41,
  "title": "GreenTech Sprint",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-41.jpg",
  "date": "2023-12-27T00:00:00",
  "venue": "Knowledge Hall, Jaipur",
  "seats": 145,
  "registered": 22
},
  {
  "id": 42,
  "title": "AR/VR Design Workshop",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-42.jpg",
  "date": "2024-01-21T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 113,
  "registered": 34
},
  {
  "id": 43,
  "title": "Python for Data Science",
  "type": "Workshop",
  "description": "Hands-on training sessions for developers and enthusiasts.",
  "image": "/images/workshop-43.jpg",
  "date": "2023-11-21T00:00:00",
  "venue": "DevHub, Chennai",
  "seats": 143,
  "registered": 47
},
  {
  "id": 44,
  "title": "AI Ethics Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-44.jpg",
  "date": "2024-02-11T00:00:00",
  "venue": "NEST, Ahmedabad",
  "seats": 70,
  "registered": 196
},
  {
  "id": 45,
  "title": "Web3 Security Seminar",
  "type": "Seminar",
  "description": "Engage with experts and gain insights on cutting-edge topics.",
  "image": "/images/seminar-45.jpg",
  "date": "2024-02-29T00:00:00",
  "venue": "Innovation Hub, Mumbai",
  "seats": 208,
  "registered": 25
},
  {
  "id": 46,
  "title": "HealthTech Challenge",
  "type": "Hackathon",
  "description": "Build innovative solutions in a fast-paced coding competition.",
  "image": "/images/hackathon-46.jpg",
  "date": "2024-03-09T00:00:00",
  "venue": "IT Convention Center, Pune",
  "seats": 193,
  "registered": 46
}
].slice(0, 6); // Ensure only 6 events


