export const EVENT_TYPES = [
  "Hackathon",
  "Seminar",
  "Workshop"
];

export const FEATURED_EVENTS = [
  {
    id: 1,
    title: "AI Innovation Hackathon",
    type: "Hackathon",
    description: "Build AI solutions for real-world problems in 48 hours.",
    image: "/skillspherejob.jpeg",
    date: "2023-12-15T09:00:00",
    venue: "Tech Park, Bangalore",
    seats: 120,
    registered: 89,
  },
  {
    id: 2,
    title: "Web3 Security Seminar",
    type: "Seminar",
    description: "Learn about blockchain security best practices.",
    image: "/skillspherejob.jpeg",
    date: "2023-11-28T14:00:00",
    venue: "Convention Center, Delhi",
    seats: 200,
    registered: 145,
  },
  {
    id: 3,
    title: "HealthTech Challenge",
    type: "Hackathon",
    description: "Build innovative solutions in a fast-paced coding competition.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-30T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 193,
    registered: 147,
  },
  {
    id: 4,
    title: "AR/VR Design Workshop",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-29T00:00:00",
    venue: "Knowledge Hall, Jaipur",
    seats: 233,
    registered: 181,
  },
  {
    id: 5,
    title: "AI Ethics Seminar",
    type: "Seminar",
    description: "Engage with experts and gain insights on cutting-edge topics.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-23T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 140,
    registered: 94,
  },
  {
    id: 6,
    title: "Next.js Masterclass",
    type: "Seminar",
    description: "Deep dive into Next.js with experts.",
    image: "/skillspherejob.jpeg",
    date: "2024-02-28T00:00:00",
    venue: "Knowledge Hall, Jaipur",
    seats: 250,
    registered: 214,
  },
  {
    id: 7,
    title: "Blockchain Basics",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-06T00:00:00",
    venue: "DevHub, Chennai",
    seats: 100,
    registered: 70,
  },
  {
    id: 8,
    title: "Docker Deep Dive",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2023-12-12T00:00:00",
    venue: "Tech Park, Bangalore",
    seats: 280,
    registered: 98,
  },
  {
    id: 9,
    title: "Next.js Masterclass",
    type: "Seminar",
    description: "Engage with experts and gain insights on cutting-edge topics.",
    image: "/skillspherejob.jpeg",
    date: "2024-02-22T00:00:00",
    venue: "Creator Space, Kochi",
    seats: 140,
    registered: 74,
  },
  {
    id: 10,
    title: "Blockchain Basics",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-19T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 281,
    registered: 78,
  },
  {
    id: 11,
    title: "HealthTech Challenge",
    type: "Hackathon",
    description: "Fast-paced coding competition for health tech solutions.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-11T00:00:00",
    venue: "DevHub, Chennai",
    seats: 230,
    registered: 192,
  },
  {
    id: 12,
    title: "Python for Data Science",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-21T00:00:00",
    venue: "DevHub, Chennai",
    seats: 213,
    registered: 33,
  },
  {
    id: 13,
    title: "Blockchain Basics",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-14T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 227,
    registered: 69,
  },
  {
    id: 14,
    title: "Blockchain Basics",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-13T00:00:00",
    venue: "DevHub, Chennai",
    seats: 203,
    registered: 119,
  },
  {
    id: 15,
    title: "Python for Data Science",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2023-11-29T00:00:00",
    venue: "IT Convention Center, Pune",
    seats: 214,
    registered: 202,
  },
  {
    id: 16,
    title: "AI Ethics Seminar",
    type: "Seminar",
    description: "Engage with experts and gain insights on cutting-edge topics.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-21T00:00:00",
    venue: "IT Convention Center, Pune",
    seats: 143,
    registered: 97,
  },
  {
    id: 17,
    title: "Future Code Hackathon",
    type: "Hackathon",
    description: "Solve future tech challenges in this fast-paced hackathon.",
    image: "/skillspherejob.jpeg",
    date: "2024-04-28T00:00:00",
    venue: "Creator Space, Kochi",
    seats: 126,
    registered: 95,
  },
  {
    id: 18,
    title: "AI Innovation Hackathon",
    type: "Hackathon",
    description: "Build innovative AI solutions in a coding marathon.",
    image: "/skillspherejob.jpeg",
    date: "2024-04-13T00:00:00",
    venue: "Tech Park, Bangalore",
    seats: 272,
    registered: 96,
  },
  {
    id: 19,
    title: "Cloud Native Seminar",
    type: "Seminar",
    description: "Explore cloud-native trends with industry experts.",
    image: "/skillspherejob.jpeg",
    date: "2023-12-27T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 213,
    registered: 174,
  },
  {
    id: 20,
    title: "Cyber Law Session",
    type: "Seminar",
    description: "Learn about the latest in digital law and security.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-19T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 207,
    registered: 53,
  },
  {
    id: 21,
    title: "AR/VR Design Workshop",
    type: "Workshop",
    description: "Hands-on AR/VR training for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-28T00:00:00",
    venue: "DevHub, Chennai",
    seats: 136,
    registered: 17,
  },
  {
    id: 22,
    title: "Blockchain Basics",
    type: "Workshop",
    description: "Practical blockchain introduction for beginners.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-20T00:00:00",
    venue: "IT Convention Center, Pune",
    seats: 263,
    registered: 142,
  },
  {
    id: 23,
    title: "React Native Bootcamp",
    type: "Workshop",
    description: "Hands-on mobile app development using React Native.",
    image: "/skillspherejob.jpeg",
    date: "2024-04-15T00:00:00",
    venue: "IT Convention Center, Pune",
    seats: 203,
    registered: 39,
  },
  {
    id: 24,
    title: "HealthTech Challenge",
    type: "Hackathon",
    description: "Fast-paced competition for healthcare innovation.",
    image: "/skillspherejob.jpeg",
    date: "2023-12-27T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 173,
    registered: 106,
  },
  {
    id: 25,
    title: "AI Innovation Hackathon",
    type: "Hackathon",
    description: "Develop AI solutions in an innovation-driven hackathon.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-18T00:00:00",
    venue: "Digital Valley, Indore",
    seats: 243,
    registered: 28,
  },
  {
    id: 26,
    title: "Next.js Masterclass",
    type: "Seminar",
    description: "Engage with experts and master Next.js.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-17T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 285,
    registered: 62,
  },
  {
    id: 27,
    title: "Cloud Native Seminar",
    type: "Seminar",
    description: "Discover modern cloud-native strategies.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-27T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 209,
    registered: 77,
  },
  {
    id: 28,
    title: "AI Innovation Hackathon",
    type: "Hackathon",
    description: "Hackathon focused on AI-based innovations.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-06T00:00:00",
    venue: "Tech Park, Bangalore",
    seats: 147,
    registered: 13,
  },
  {
    id: 29,
    title: "React Native Bootcamp",
    type: "Workshop",
    description: "Learn mobile app development in this bootcamp.",
    image: "/skillspherejob.jpeg",
    date: "2024-02-26T00:00:00",
    venue: "Digital Valley, Indore",
    seats: 162,
    registered: 111,
  },
  {
    id: 30,
    title: "Cloud Native Seminar",
    type: "Seminar",
    description: "Engage with cloud experts and learn modern practices.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-14T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 285,
    registered: 57,
  },
  {
    id: 31,
    title: "GreenTech Sprint",
    type: "Hackathon",
    description: "Build sustainable solutions in this coding sprint.",
    image: "/skillspherejob.jpeg",
    date: "2023-11-18T00:00:00",
    venue: "Tech Park, Bangalore",
    seats: 73,
    registered: 14,
  },
  {
    id: 32,
    title: "Blockchain Basics",
    type: "Workshop",
    description: "Blockchain workshop for beginners and developers.",
    image: "/skillspherejob.jpeg",
    date: "2023-12-30T00:00:00",
    venue: "Tech Park, Bangalore",
    seats: 270,
    registered: 243,
  },
  {
    id: 33,
    title: "Blockchain Basics",
    type: "Workshop",
    description: "Hands-on blockchain training for enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2023-11-14T00:00:00",
    venue: "Creator Space, Kochi",
    seats: 273,
    registered: 172,
  },
  {
    id: 34,
    title: "Next.js Masterclass",
    type: "Seminar",
    description: "Gain deep insights into Next.js development.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-22T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 240,
    registered: 205,
  },
  {
    id: 35,
    title: "AR/VR Design Workshop",
    type: "Workshop",
    description: "Learn AR/VR design through hands-on practice.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-11T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 172,
    registered: 94,
  },
  {
    id: 36,
    title: "React Native Bootcamp",
    type: "Workshop",
    description: "Bootcamp on React Native mobile apps.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-24T00:00:00",
    venue: "Digital Valley, Indore",
    seats: 230,
    registered: 86,
  },
  {
    id: 37,
    title: "SpaceTech Hack",
    type: "Hackathon",
    description: "Hackathon for innovative space technology ideas.",
    image: "/skillspherejob.jpeg",
    date: "2024-04-03T00:00:00",
    venue: "Digital Valley, Indore",
    seats: 223,
    registered: 51,
  },
  {
    id: 38,
    title: "AI Innovation Hackathon",
    type: "Hackathon",
    description: "AI innovation sprint for developers and teams.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-23T00:00:00",
    venue: "Creator Space, Kochi",
    seats: 88,
    registered: 45,
  },
  {
    id: 39,
    title: "Web3 Security Seminar",
    type: "Seminar",
    description: "Best practices for blockchain and Web3 security.",
    image: "/skillspherejob.jpeg",
    date: "2024-02-10T00:00:00",
    venue: "Startup Arena, Hyderabad",
    seats: 285,
    registered: 153,
  },
  {
    id: 40,
    title: "Docker Deep Dive",
    type: "Workshop",
    description: "Learn advanced Docker usage in practice.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-09T00:00:00",
    venue: "Digital Valley, Indore",
    seats: 195,
    registered: 157,
  },
  {
    id: 41,
    title: "GreenTech Sprint",
    type: "Hackathon",
    description: "Hackathon for green and sustainable technologies.",
    image: "/skillspherejob.jpeg",
    date: "2023-12-27T00:00:00",
    venue: "Knowledge Hall, Jaipur",
    seats: 145,
    registered: 22,
  },
  {
    id: 42,
    title: "AR/VR Design Workshop",
    type: "Workshop",
    description: "Explore AR/VR design with practical exercises.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-21T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 113,
    registered: 34,
  },
  {
    id: 43,
    title: "Python for Data Science",
    type: "Workshop",
    description: "Introductory workshop on Python for data analysis.",
    image: "/skillspherejob.jpeg",
    date: "2023-11-21T00:00:00",
    venue: "DevHub, Chennai",
    seats: 143,
    registered: 47,
  },
  {
    id: 44,
    title: "AI Ethics Seminar",
    type: "Seminar",
    description: "Discuss the ethics of AI with experts.",
    image: "/skillspherejob.jpeg",
    date: "2024-02-11T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 196,
    registered: 70,
  },
  {
    id: 45,
    title: "Web3 Security Seminar",
    type: "Seminar",
    description: "Security challenges and solutions in Web3.",
    image: "/skillspherejob.jpeg",
    date: "2024-02-29T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 208,
    registered: 25,
  }
];
