export const EVENT_TYPES = [
  "Hackathon",
  "Seminar",
  "Workshop"
];

export const FEATURED_EVENTS = [
  {
    id: 1,
    title: "AI Innovation Hackathon",
    type: "Hackathon",
    description: "Build AI solutions for real-world problems in 48 hours.",
    image: "/skillspherejob.jpeg",
    date: "2023-12-15T09:00:00",
    venue: "Tech Park, Bangalore",
    seats: 120,
    registered: 89,
  },
  {
    id: 2,
    title: "Web3 Security Seminar",
    type: "Seminar",
    description: "Learn about blockchain security best practices.",
    image: "/skillspherejob.jpeg",
    date: "2023-11-28T14:00:00",
    venue: "Convention Center, Delhi",
    seats: 200,
    registered: 145,
  },
  {
    id: 3,
    title: "HealthTech Challenge",
    type: "Hackathon",
    description: "Build innovative solutions in a fast-paced coding competition.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-30T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 193,
    registered: 147,
  },
  {
    id: 4,
    title: "AR/VR Design Workshop",
    type: "Workshop",
    description: "Hands-on training sessions for developers and enthusiasts.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-29T00:00:00",
    venue: "Knowledge Hall, Jaipur",
    seats: 233,
    registered: 181,
  },
  {
    id: 5,
    title: "AI Ethics Seminar",
    type: "Seminar",
    description: "Engage with experts and gain insights on cutting-edge topics.",
    image: "/skillspherejob.jpeg",
    date: "2024-01-23T00:00:00",
    venue: "NEST, Ahmedabad",
    seats: 140,
    registered: 94,
  },
  {
    id: 6,
    title: "Next.js Masterclass",
    type: "Seminar",
    description: "Deep dive into Next.js with experts.",
    image: "/skillspherejob.jpeg",
    date: "2024-02-28T00:00:00",
    venue: "Knowledge Hall, Jaipur",
    seats: 250,
    registered: 214,
  },
  {
    id: 7,
    title: "Cloud Computing Workshop",
    type: "Workshop",
    description: "Explore cloud technologies and their applications.",
    image: "/skillspherejob.jpeg",
    date: "2024-03-15T00:00:00",
    venue: "Tech Park, Bangalore",
    seats: 150,
    registered: 120,
  },
  {
    id: 8,
    title: "Cybersecurity Awareness Workshop",
    type: "Workshop",
    description: "Learn about the latest trends in cybersecurity.",
    image: "/skillspherejob.jpeg",
    date: "2024-04-20T00:00:00",
    venue: "Innovation Hub, Mumbai",
    seats: 100,
    registered: 75,
  },
  {
    id: 9,
    title: "AI for Good Summit",
    type: "Seminar",
    description: "Discuss the ethical implications of AI technologies.",
    image: "/skillspherejob.jpeg",
    date: "2024-05-10T00:00:00",
    venue: "Global Impact Center, New York",
    seats: 300,
    registered: 250,
  },

];
